### ISSUE TITLE
support alert manager "active_time_intervals"

### ISSUE THREAD

**Issue by elasticdotventures** [aws/amazon-managed-service-for-prometheus-roadmap#26]
Amazon Managed Prometheus does not appear to support the "active_time_intervals" setting/behavior.   

```
│ Error: waiting for Prometheus Alert Manager Definition (ws-xxxxxx) update: unexpected state 'UPDATE_FAILED', wanted target 'ACTIVE'. last error: status=400, message=error validating Alertmanager config: yaml: unmarshal errors:
│   line 41: field active_time_intervals not found in type config.plain
```

`mute_time_intervals` seems to work, but generally this cortex product appears to diverge in annoying and inconvenient ways from the stock (well documented) versions of Prometheus & mimir.   

A sample config is below (mute_time_intervals is accepted, active_time_intervals is not)

```
  # Times when the route should be active. These must match the name of a
  # time interval defined in the time_intervals section. An empty value
  # means that the route is always active.
  # Additionally, the root node cannot have any active times.
  # The route will send notifications only when active, but otherwise
  # acts normally (including ending the route-matching process
  # if the `continue` option is not set).    
  active_time_intervals:
    - name: offhours
      time_intervals:
        - weekdays: ['Saturday','Sunday']
        - times:
          - start_time: '00:00'
            end_time: '09:00'
          - start_time: '18:00'
            end_time: '24:00'

  # Times when the route should be muted. These must match the name of a
  # mute time interval defined in the mute_time_intervals section.
  # Additionally, the root node cannot have any mute times.
  # When a route is muted it will not send any notifications, but
  # otherwise acts normally (including ending the route-matching process
  # if the `continue` option is not set.)
  mute_time_intervals:
    - name: offhours
      time_intervals:
        - weekdays: ['Saturday','Sunday']
        - times:
          - start_time: '00:00'
            end_time: '09:00'
          - start_time: '18:00'
            end_time: '24:00'
```
