### ISSUE TITLE
fix documentation

### ISSUE THREAD

**Issue by elasticdotventures** [aws/amazon-managed-service-for-prometheus-roadmap#36]
on the AWS managed docs page the receiver config has two issues with the sample configuration for receivers is wrong.

https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-receiver-config.html

firstly, the format is not 
key: key, value: value

I've verified the prometheus docs are correct:
* https://prometheus.io/docs/alerting/latest/configuration/#sns_configs
attributes are:
key1: value1
key2: value2

secondly, the proposed indentation for the sigv4: should not have a - .. I think that would actually break it.  This is taken from a working config:

```
  receivers:
    - name: 'opsgenie-sns'
      sns_configs:
        - topic_arn: "replace_arn"
          send_resolved: false
          subject: '{{ template "opsgenie.default.subject" .}}'
          message: ''
          sigv4:
            region: "${region}"
          attributes:
            tags: '{{ template "__opsgenie_tags" .Alerts.Firing }}'
            teams: '{{ template "__opsgenie_teams" .Alerts.Firing }}'
            priority: '{{ template "__opsgenie_priority" .CommonLabels.SortedPairs }}'
```
