### ISSUE TITLE
Default alert manager templates get overwritten by the content of `message` field

### ISSUE THREAD

**Issue by maulikpandey** [aws/amazon-managed-service-for-prometheus-roadmap#7]
According to [AWS documentation](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-receiver-JSON.html) we can use templates to produce JSON based output from alert manager. But in practice the output of templates get overwritten by the content of the `message` field of the `sns_configs`. 

We need the `message` field content for [integrating](https://aws.amazon.com/blogs/mt/using-amazon-managed-service-for-prometheus-alert-manager-to-receive-alerts-with-pagerduty/) with Pagerduty and Slack. We are currently over coming this limitation by using the templating language to create blocks in the `message` field.

**Comment by ampabhi-aws** [comment]
Hey @maulikpandey,

Thank you for posting this feature request! I wanted to double click on a few items:

(1) Do you need JSON to be embedded as a sub piece of your message field? Usually, we find that customers want to send the payload as entirely JSON or want to customize the YAML body. 

(2) If we provided a JSON function rather than a message override in the documentation, would that solve the issue? How would you use the new function?

**Comment by maulikpandey** [comment]
(1) Entire payload as a JSON.
(2) A JSON function that tells Alert Manager to output a JSON payload (instead of YAML) is sufficient for my use case.

**Comment by ampabhi-aws** [comment]
For anyone else who comes across this issue, you can structure the entire payload as JSON through the template snippet in the [AWS Documentation](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-receiver-JSON.html). 

We are discussing ways of improving the toJSON capabilities as can be seen in this Prometheus community discussion: https://github.com/prometheus/alertmanager/issues/2678.

**Comment by Ulrar** [comment]
I'm probably missing something, but I can't get it working using the template in the doc linked by @ampabhi-aws : 

```
default_template: |
   {{ define "sns.default.message" }}{{ "{" }}"receiver": "{{ .Receiver }}","status": "{{ .Status }}","alerts": [{{ range $alertIndex, $alerts := .Alerts }}{{ if $alertIndex }}, {{ end }}{{ "{" }}"status": "{{ $alerts.Status }}"{{ if gt (len $alerts.Labels.SortedPairs) 0 -}},"labels": {{ "{" }}{{ range $index, $label := $alerts.Labels.SortedPairs }}{{ if $index }}, {{ end }}"{{ $label.Name }}": "{{ $label.Value }}"{{ end }}{{ "}" }}{{- end }}{{ if gt (len $alerts.Annotations.SortedPairs ) 0 -}},"annotations": {{ "{" }}{{ range $index, $annotations := $alerts.Annotations.SortedPairs }}{{ if $index }}, {{ end }}"{{ $annotations.Name }}": "{{ $annotations.Value }}"{{ end }}{{ "}" }}{{- end }},"startsAt": "{{ $alerts.StartsAt }}","endsAt": "{{ $alerts.EndsAt }}","generatorURL": "{{ $alerts.GeneratorURL }}","fingerprint": "{{ $alerts.Fingerprint }}"{{ "}" }}{{ end }}]{{ if gt (len .GroupLabels) 0 -}},"groupLabels": {{ "{" }}{{ range $index, $groupLabels := .GroupLabels.SortedPairs }}{{ if $index }}, {{ end }}"{{ $groupLabels.Name }}": "{{ $groupLabels.Value }}"{{ end }}{{ "}" }}{{- end }}{{ if gt (len .CommonLabels) 0 -}},"commonLabels": {{ "{" }}{{ range $index, $commonLabels := .CommonLabels.SortedPairs }}{{ if $index }}, {{ end }}"{{ $commonLabels.Name }}": "{{ $commonLabels.Value }}"{{ end }}{{ "}" }}{{- end }}{{ if gt (len .CommonAnnotations) 0 -}},"commonAnnotations": {{ "{" }}{{ range $index, $commonAnnotations := .CommonAnnotations.SortedPairs }}{{ if $index }}, {{ end }}"{{ $commonAnnotations.Name }}": "{{ $commonAnnotations.Value }}"{{ end }}{{ "}" }}{{- end }}{{ "}" }}{{ end }}
   {{ define "sns.default.subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]{{ end }}
alertmanager_config: |
  templates:
    - 'default_template'
  route:
    receiver: 'default'
  receivers:
    - name: 'default'
      sns_configs:
        - topic_arn: '<my topic arn>'
          send_resolved: true
          sigv4:
            region: '<my region>'
```

This applies fine but the messages get to the SNS Topic with the default space separated template.
Is there something else needed that I may have missed ?
